export const makes = [
    "Maruti_Suzuki",
    "Hyundai",
    "Tata",
    "Mahindra",
    "Kia",
    "Toyota",
    "Honda",
    "Ford",
    "Volkswagen",
    "Renault",
    "Nissan",
    "MG",
    "Skoda",
    "Jeep",
    "Fiat",
    "Datsun",
    "Isuzu",
    "Mitsubishi",
    "Citroen",
    "Lexus",
    "Peugeot",
    "Mini",
    "Chevrolet",
    "Daewoo",
    "Opel",
    "SsangYong",
    "Genesis",
    "BYD",
    "Great_Wall_Motors",
    "Haval",
    "Force_Motors",
    "Ashok_Leyland",
    "Premier",
    "Hindustan_Motors",
    "Morris_Garages",
    "Porsche",
    "Jaguar",
    "Land_Rover",
    "Volvo",
    "BMW",
    "Audi",
    "Mercedes_Benz",
    "Bentley",
    "Rolls_Royce",
    "Ferrari",
    "Lamborghini",
    "Bugatti",
  ];

export const models = {
    Maruti_Suzuki: [
      "Alto",
      "Swift",
      "Baleno",
      "Dzire",
      "Vitara Brezza",
      "Celerio",
      "Ertiga",
      "S-Cross",
      "Ignis",
      "Wagon R",
    ],
    Hyundai: [
      "i10",
      "i20",
      "Creta",
      "Verna",
      "Venue",
      "Sonata",
      "Elantra",
      "Tucson",
      "Kona",
      "Grand i10",
    ],
    Tata: [
      "Nexon",
      "Harrier",
      "Altroz",
      "Tiago",
      "Tigor",
      "Safari",
      "Hexa",
      "Punch",
      "Zest",
      "Bolt",
    ],
    Mahindra: [
      "XUV700",
      "Thar",
      "Scorpio",
      "Bolero",
      "XUV300",
      "Marazzo",
      "Alturas G4",
      "KUV100",
      "TUV300",
    ],
    Kia: ["Seltos", "Sonet", "Carnival", "Xceed", "K5", "Sportage"],
    Toyota: [
      "Innova Crysta",
      "Fortuner",
      "Urban Cruiser",
      "Corolla Altis",
      "Camry",
      "Yaris",
      "Glanza",
    ],
    Honda: ["City", "Jazz", "Amaze", "WR-V", "CR-V", "BR-V", "Civic"],
    Ford: ["EcoSport", "Endeavour", "Figo", "Aspire", "Mustang"],
    Volkswagen: ["Polo", "Tiguan", "Vento", "Passat", "Virtus"],
    Renault: ["Kwid", "Triber", "Duster", "Captur", "Lodgy"],
    Nissan: ["Micra", "Magnite", "Kicks", "Sunny", "Terrano"],
    MG: ["Hector", "ZS EV", "Gloster", "Astor"],
    Skoda: ["Rapid", "Octavia", "Kushaq", "Superb", "Fabia"],
    Jeep: ["Compass", "Wrangler", "Grand Cherokee", "Cherokee"],
    Fiat: ["Punto", "Linea", "500", "Avventura"],
    Datsun: ["Redi-Go", "Go", "Go Plus"],
    Isuzu: ["D-Max", "MU-X"],
    Mitsubishi: ["Pajero", "Outlander", "Lancer"],
    Mercedes_Benz: [
      "A-Class",
      "C-Class",
      "E-Class",
      "S-Class",
      "GLA",
      "GLC",
      "GLE",
      "SLC",
      "CLA",
      "Maybach",
    ],
    BMW: [
      "X1",
      "X3",
      "X5",
      "X7",
      "3 Series",
      "5 Series",
      "7 Series",
      "M3",
      "M5",
      "Z4",
    ],
    Audi: ["Q3", "Q5", "Q7", "Q8", "A3", "A4", "A6", "A8", "RS5", "A7"],
    Jaguar: ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace"],
    "Land Rover": [
      "Discovery",
      "Range Rover",
      "Range Rover Sport",
      "Evoque",
      "Defender",
    ],
    Volvo: ["XC40", "XC60", "XC90", "S60", "S90"],
    Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan"],
    Ferrari: ["488 GTB", "Portofino", "Roma", "F8 Tributo"],
    Lamborghini: ["Aventador", "Huracán", "Urus"],
    Bentley: ["Continental GT", "Flying Spur", "Bentayga"],
    Rolls_Royce: ["Phantom", "Ghost", "Cullinan", "Wraith", "Dawn"],
    Maserati: ["Quattroporte", "Ghibli", "Levante", "GranTurismo"],
    Bugatti: ["Chiron", "Veyron"],
    Mini: ["Cooper", "Countryman"],
    Chevrolet: ["Beat", "Cruze", "Sail", "Captiva"],
    Daewoo: ["Matiz", "Cielo", "Nexia"],
    Opel: ["Astra", "Corsa", "Mokka"],
    Peugeot: ["3008", "5008"],
    Ashok_Leyland: ["Stile", "Commando", "Dost", "Buss"],
    Force_Motors: ["Trax", "Traveller", "Gurkha", "One"],
    Premier: ["Padmini", "Rio"],
    Hindustan_Motors: ["Ambassador", "Contessa"],
    Morris_Garages: ["MG Hector", "MG ZS EV"],
    Citroen: ["C3", "C5 Aircross"],
    Lexus: ["RX", "NX", "ES", "LX"],
    Infiniti: ["QX50", "QX60", "Q70", "QX80"],
    SsangYong: ["Rexton", "Tivoli", "Korando"],
    Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
    Haval: ["H2", "H6", "F7"],
    BYD: ["e6", "Atto 3"],
    Great_Wall_Motors: ["Haval H6", "Tank 300"],
    Changan: ["CS35", "CS75", "UNI-T"],
  };

export const variants = {
    Corolla: ["LE", "SE", "XSE"],
    Camry: ["LE", "XLE", "TRD"],
    RAV4: ["LE", "XLE", "Limited"],
    Civic: ["LX", "Sport", "Touring"],
    Accord: ["LX", "Sport", "Touring"],
    CR_V: ["LX", "EX", "Touring"],
    Fiesta: ["S", "SE", "Titanium"],
    Focus: ["S", "SE", "Titanium"],
    Mustang: ["EcoBoost", "GT", "Mach 1"],
    sample: ["Base", "Mid", "Top", "Base-AT", "Mid-AT", "Top-AT"],
  };